styling and fixes
b3rs3rk/gpustat-unraid pull request #10
Opened 2021-01-06 17:12 UTC by mlapaglia

2021-01-06 18:38 UTC, b3rs3rk requested changes
Address issues in two bottom-most comments.  Top one is an atta-boy.  Nice work overall.  Looks a lot cleaner on the display side of the code.  Once issues are addressed I will checkout locally and test with my 6.8.3 intall for backwards compatibility.  If it all works, I'll approve and merge the PR to dev and begin the package creation process.  Thanks!

2021-01-06 18:38 UTC, b3rs3rk commented on src/gpustat/usr/local/emhttp/plugins/gpustat/lib/Nvidia.php
> +                    $retval['memutil'] = round($retval['memused'] / $retval['memtotal'] * 100) . "%";
If fb_memory_usage->free is set, does that guarantee total and used will also be set?  Usually bad form to test data viability that way.  Consider moving to:

```php
isset($gpu->fb_memory_usage->used) && isset($gpu->fb_memory_usage->total)
```

2021-01-06 18:38 UTC, b3rs3rk commented on src/gpustat/usr/local/emhttp/plugins/gpustat/lib/Nvidia.php
> +                    $retval['memclockmax'] = (string) str_replace(' MHz', '', $gpu->max_clocks->mem_clock);
Is memory max_clocks a guaranteed element for all cards?  Might want to make sure we individually check that this one is set before we attempt to use it separate from the clocks since it has a different parent endpoint.

```php
if (isset($gpu->max_clocks->mem_clock)) {
    $retval['memclockmax'] = (string) str_replace(' MHz', '', $gpu->max_clocks->mem_clock);
}
```

There's been a few instances so far where I assumed that all cards would provide endpoints for all values, even if they didn't report any value data for it (or listed it as N/A from the nvidia-smi output).  Doing isset before it will prevent a future bug.

2021-01-06 18:38 UTC, b3rs3rk commented on src/gpustat/usr/local/emhttp/plugins/gpustat/GPUStatSettings.page
> +  </select>
This is much cleaner than the way I did it.  I guess I didn't RTFM when it came to developing a plugin for UnRAID.  Kudos.

2021-01-06 18:42 UTC, b3rs3rk commented
@mlapaglia Not sure if you know this, but don't close the PR to make changes.  Leave it open, and just make new commits/pushes to your branch.  They will automatically reflect here.

2021-01-06 18:54 UTC, b3rs3rk commented on src/gpustat/usr/local/emhttp/plugins/gpustat/lib/Nvidia.php
> +                'memclockmax'   => 'N/A',
Please normalize spacing for these.  Since memclockmax pushes it out further, just tab out all of the other => to the same distance as memclockmax.

2021-01-06 19:12 UTC, mlapaglia commented on src/gpustat/usr/local/emhttp/plugins/gpustat/GPUStatSettings.page
> +  </select>
i didn't RTFM either, i don't think there is one, i just copied what unraid has in the CPU stats html

2021-01-06 19:14 UTC, mlapaglia commented on src/gpustat/usr/local/emhttp/plugins/gpustat/GPUStatSettings.page
> +  </select>
i didn't RTFM either, i don't think there is one, i just copied what other plugins used.

2021-01-06 19:14 UTC, mlapaglia commented
> @mlapaglia Not sure if you know this, but don't close the PR to make changes. Leave it open, and just make new commits/pushes to your branch. They will automatically reflect here.

if i delete my local repo and refork it the pr has to close right?

2021-01-06 21:04 UTC, b3rs3rk commented
> 
> 
> > @mlapaglia Not sure if you know this, but don't close the PR to make changes. Leave it open, and just make new commits/pushes to your branch. They will automatically reflect here.
> 
> if i delete my local repo and refork it the pr has to close right?

You don't need to delete local and refork everytime.  I only suggested that first time because of all the boo boos you had with attempting to make the package and the file/replace issues.  From here, just evaluate my review, fix anything requested in your local branch, commit and push.  Your changes will populate in this PR automatically.

2021-01-07 21:55 UTC, b3rs3rk approved these changes

2021-01-07 21:59 UTC, merged