SUPPORTED_APPS
b3rs3rk/gpustat-unraid pull request #30
Opened 2021-11-18 18:52 UTC by corgan2222

- nsfminer
- shinobipro shinobi-face

2021-11-18 18:53 UTC, corgan2222 commented
I hope this time the PR is correct. :)

2021-11-18 21:48 UTC, b3rs3rk requested changes
Review comments, just need the file for nsfminer lowercased

2021-11-18 21:48 UTC, b3rs3rk commented on src/gpustat/usr/local/emhttp/plugins/gpustat/gpustatus.page
> +                    <img id='gpu-nsfminer' class='gpu-image' src="/plugins/gpustat/images/NsfminerOC.png">
Need to lowercase the name for this! NsfminerOC.png -> nsfmineroc.png -- you will need to change the file name as well and push that commit.  PR should update automatically and then I can merge.

2021-11-18 22:35 UTC, corgan2222 commented on src/gpustat/usr/local/emhttp/plugins/gpustat/gpustatus.page
> +                    <img id='gpu-nsfminer' class='gpu-image' src="/plugins/gpustat/images/NsfminerOC.png">
fixed :)

2021-11-18 22:37 UTC, corgan2222 commented
Should be fixed.

2021-11-21 21:20 UTC, b3rs3rk approved these changes
Looks good!  Thanks for the contribution.  I'll try to get a new release out in the next few days.

2021-11-21 21:20 UTC, merged